# Usa a imagem oficial do Node.js para construir o Angular
FROM node:23 AS build

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos do projeto Angular para o container
COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Compila o Angular para produção
RUN npm run build --prod

# Usa a imagem do Nginx para servir o Angular
FROM nginx:alpine

# Copia os arquivos compilados do Angular para a pasta do Nginx
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html

# Copia o arquivo de configuração do Nginx para dentro do container
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expõe a porta 80
EXPOSE 80

# Inicia o Nginx
CMD ["nginx", "-g", "daemon off;"]
